spring:
  config:
    activate:
      on-profile: prod
    servlet:
      multipart:
        max-file-size: 1GB
        max-request-size: 1GB

  springdoc:
    api-docs:
      path: /v3/api-docs # OpenAPI spec JSON 위치
    swagger-ui:
      path: /swagger-ui # 접속 경로
      config-url: /v3/api-docs/swagger-config

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIA_DATABASE_URL}
    username: ${MARIA_USER}
    password: ${MARIA_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 180000 # 3분 
      max-lifetime: 240000 # 4분 
      keepalive-time: 60000 # 1분
      connection-timeout: 15000 # 15초
      validation-timeout: 2000 # 2초
      auto-commit: false
      pool-name: HikariCP-Local
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect # mariadb
      org.hibernate.envers.store_data_at_delete: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ADDRESS}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

management:
  endpoints:
    web:
      exposure:
        include: health

initializer:
  enable: true

file:
  upload:
    base-path: /app/storage
    mockup-path: /app/storage/mockups
    spec-save-path: /app/storage/mockups
    asis-path: /app/storage/asis
    asis-save-path: /app/storage/asis
    upload-path: /app/storage/uploads

mockup:
  callback-url: "https://decase.skala25a.project.skala-ai.com/api/v1/projects/{projectId}/mockups/callback"

screen-spec:
  callback-url: "https://decase.skala25a.project.skala-ai.com/api/v1/projects/{projectId}/screen-spec/callback"

asis:
  callback-url: "https://decase.skala25a.project.skala-ai.com/api/v1/projects/{projectId}/asis/callback"

srs:
  callback-url: "https://decase.skala25a.project.skala-ai.com/api/v1/projects/{projectId}/srs-agent/callback"

srs-update:
  callback-url: "https://decase.skala25a.project.skala-ai.com/api/v1/projects/{projectId}/srs-agent/update/callback"

invite:
  web-url: "https://decase.skala25a.project.skala-ai.com/invite"
