spring:
  application:
    name: decase
  profiles:
    active: prod
  config:
    import: optional:file:.env.properties
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

mockup:
  callback-url: "http://localhost:8080/api/v1/projects/{projectId}/mockups/callback"
