spring:
  application:
    name: decase
  profiles:
    active: local
  config:
    import: optional:file:.env.properties
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

springdoc:
  api-docs:
    path: /swagger/v3/api-docs # OpenAPI spec JSON 위치
  swagger-ui:
    path: /swagger/swagger-ui.html # 접속 경로
    operationsSorter: alpha # 정렬 방식 (alpha, method 등)
    tagsSorter: alpha
    display-request-duration: true
    doc-expansion: none # tag별 기본 접힘(none), 열림(list), 전체(expanded)
    try-it-out-enabled: true
