spring:
  application:
    name: decase
  profiles:
    active: prod
  config:
    import: optional:file:.env.properties
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

springdoc:
  api-docs:
    path: /swagger/api-docs # OpenAPI spec JSON 위치
  swagger-ui:
    path: /swagger-ui # 접속 경로

mockup:
  callback-url: "http://localhost:8080/api/v1/projects/{projectId}/mockups/callback"
