spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIA_DATABASE_URL}
    username: ${MARIA_USER}
    password: ${MARIA_PASSWORD}

    # HikariCP 커넥션 풀 설정
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: false
      pool-name: HikariCP-Local
      leak-detection-threshold: 60000

  # JPA 로컬 설정
  jpa:
    hibernate:
      ddl-auto: update  # 로컬에서는 자동 스키마 업데이트
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect # mariadb
#        dialect: org.hibernate.dialect.MySQL8Dialect # mysql
    show-sql: true

  # actuator
  management:
    endpoints:
      web:
        exposure:
          include: health