spring:
  config:
    activate:
      on-profile: local

  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIA_DATABASE_URL}
    username: ${MARIA_USER}
    password: ${MARIA_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: false
      pool-name: HikariCP-Local
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect # mariadb
#          dialect: org.hibernate.dialect.MySQL8Dialect # mysql
      org.hibernate.envers.store_data_at_delete: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ADDRESS}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

management:
  endpoints:
    web:
      exposure:
        include: health

file:
  upload:
    # base-path: ${FILE_STORAGE_PATH:/shared/documents}
    # mockup-path: ${file.upload.base-path}/mockup
    # asis-path: ${file.upload.base-path}/asis
    # upload-path: ${file.upload.base-path}/uploads
    base-path: ${FILE_STORAGE_PATH}
    mockup-path: ${MOCKUP_STORAGE_PATH}
    asis-path: ${ASIS_STORAGE_PATH}
    upload-path: ${UPLOADS_STORAGE_PATH}
