spring:
  application:
    name: decase
  profiles:
    active: local
  config:
    import: optional:file:.env.properties
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
