apiVersion: apps/v1
kind: Deployment
metadata:
  name: decase
  namespace: sk-team-08
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decase
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/actuator/prometheus"
        update: 5e59d2ee47d1c85987208efb0e91a711
      labels:
        app: decase
    spec:
      serviceAccountName: default
      # 초기화 컨테이너로 디렉토리 생성
      initContainers:
        - name: init-storage
          image: amdp-registry.skala-ai.com/skala25a/sk-team-08-decase:1.0.0-57-97f1ab3cb4da
          command:
            - /bin/sh
            - -c
            - |
              echo "Initializing EFS storage directories..."
              mkdir -p /app/storage/mockups /app/storage/asis /app/storage/uploads
              chmod -R 777 /app/storage
              ls -la /app/storage
              echo "EFS Storage initialization complete"
          volumeMounts:
            - name: storage-volume
              mountPath: /app/storage

      containers:
        - name: decase
          image: amdp-registry.skala-ai.com/skala25a/sk-team-08-decase:1.0.0-57-97f1ab3cb4da
          imagePullPolicy: Always
          # 볼륨 마운트 설정 (EFS)
          volumeMounts:
            - name: storage-volume
              mountPath: /app/storage # Spring Boot의 ./storage와 매핑
          env:
            # Spring Profile 설정
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: MARIA_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: decase-secret
                  key: MARIA_DATABASE_URL
            - name: MARIA_USER
              valueFrom:
                secretKeyRef:
                  name: decase-secret
                  key: MARIA_USER
            - name: MARIA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: decase-secret
                  key: MARIA_PASSWORD
            - name: MAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: decase-secret
                  key: MAIL_ADDRESS
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: decase-secret
                  key: MAIL_PASSWORD
            # 파일 업로드 설정
            - name: FILE_UPLOAD_BASE_PATH
              value: "/app/storage"
            - name: FILE_UPLOAD_MOCKUP_PATH
              value: "/app/storage/mockups"
            - name: FILE_UPLOAD_ASIS_PATH
              value: "/app/storage/asis"
            - name: FILE_UPLOAD_UPLOAD_PATH
              value: "/app/storage/uploads"
          envFrom:
            - secretRef:
                name: decase-secret

      # 볼륨 설정 (EFS PVC 사용)
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: decase-efs-sc-pvc
